const strings = {
    general: {
        en: {
            payment_info: 'Payment Information',
            not_found_page:'Sorry, The Page Not Found',
            not_found_text:'The page you are looking for may have been removed or not exist',
            not_found_action:'back to homepage',
            no_result_found_text:'No result found for your search',
            search_result:'Search Result',
            close:'Close',
            
        },
        ar: {
            payment_info: 'بيانات الدفع',
            not_found_page:'عذراً الصفحة غير موجودة',
            not_found_text:'ربما يكون قد تم حذفها أو غير موجودة أصلاً',
            not_found_action:'العودة إلى الصفحة الرئيسية',
            no_result_found_text:'لا يوجد نتائج للبحث الخاص بك',
            search_result:'نتائج البحث',
            close:'غلق',
            overview_online_courses_header:"دورات تدريبية مسجلة عن بعد",
            overview_books_included_header:"كتب وبرامج",
            overview_discount_included_header:"خصومات",
            overview_support_included_header:"دعم فنى",
            overview_online_courses:"تستطيع أن تحضر الدورات أون لاين مسجلة عن بعد من أي مكان بالعالم بجودة عالية الدقة صوتًا وصورة.",
            overview_books_included:"تستطيع الحصول على ملفات وبرامج وكتب هدايا مجانية مع الدورات التدريبية.",
            overview_discount_included:"خصومات كبيرة على الأجهزة والمعدات للحاصلين على الدورات التدريبية",
            overview_support_included:"دعم فني على مدار 12 ساعة يوميًا",
        }
    },
    client:{
        en:{
            info:'My Info',
            orders:'Orders',
            courses:'Courses',
            favourite:'Favourite',
            basic_info:'BASIC INFORMATION',
            change_pass:'CHANGE YOUR PASSWORD',
            update_address:'MODIFY YOUR ADDRESS BOOK ENTIRES',
            first_name:'First Name',
            first_name_holder:'write your first name',
            last_name:'Last Name',
            last_name_holder:'write your last name',
            contact_info:'Contact Information',
            mobile:'Mobile',
            mobile_holder:'write your mobile number',
            email:'E-mail',
            email_holder:'write your e-mail',
            pass:'Password',
            pass_holder:'enter your password',
            old_pass:'Old Password',
            old_pass_holder:'Type the Old Password',
            new_pass:'New Password',
            new_pass_holder:'Type the New Password',
            confirm_pass:'Confirm Password',
            confirm_pass_holder:'Type the New Password again',
            no_address:'There is no Addresses',
            add_address_now:'Add your Address now',
            add_address:'Add Address',
            address_error:'The Address Line is Required',
            city_error:'The City is Required',
            state_error:'The Province/State/Region is Required',
            country_error:'The Country is Required',
            postalCode_error:'The Postal Code is Required',
            address_line:'Address Line',
            address_line_holder:'Enter address line',
            country_select:'Select Your Country',
            state_enter:'Enter Your Province/State/Region',
            state_enter_holder:'Enter your province/state/region',
            city_enter:'Enter Your City',
            city_enter_holder:'Enter your city',
            postal_enter:'Enter Your Postal Code',
            postal_enter_holder:'Enter your postal code',
            update:'Update',
            submit:'Submit',
            save:'Save',
            order_history:'ORDER HISTORY',
            downloads:'DOWNLOADS',
            returns:'RETURNS',
            payment_profile:'PAYMENT PROFILE',
            order_no:'Order No',
            order_at:'Ordered At',
            payment_method:'Payment Method',
            total:'Total Price',
            items_show:'Show Items',
            no_favourite:'There is no Favourite Product yet',
            browse_product:'Browse the products',
            item:'Item',
            price:'Price',
            cart_add:'Add to Cart',
            delete:'Delete',  
            sign_in:'sign in',
            sign_up:'sign up',    
            new_signup:'Sign Up for a new Account',
            already_user:'Already have an account',
            full_name:'Full Name',
            email_address:'E-mail Address',
            phone:'Phone Number',
            phone_holder:'enter your phone number',
            agree_statement:'I Agree all statements in',
            terms_of_service:'terms of services',
            terms_of_sales:'terms of sales!',
            or_signup:'Or sign up with',
            or_signin:'Or sign in with',
            pass_rule:'Password must be at least eight characters, at least one uppercase letter, one lowercase letter, one number and one special character',
            provide_data:'please provide the required data',
            is_required:'please write',
            pass_nomatch:'Password doesn\'t match please try again',
            is_agree:'Please Agree The Terms of services & Terms of sales!',
            email_enter:'Enter your E-mail here',
            reset_link:'Send Reset link',
            remember_me:'Remember me',
            pass_forget:'Forget your password?',
            no_account:'Don\'t have account?',
            new_account:'Create Account',
            went_wrong:'something went wrong, please try again',
            payment_cancel:'Payment Process has been canceled',
            verify_email:'Congratulation, Your E-mail has been verified',
            main_page_redirect:'Redirecting to login page in 5 seconds',
            invalid_token:'The token isn\'t valid, please provide a valid one',
            not_match_pass:'The Password isn\'t match, Please write the password again',
            reset_pass_done:'Congratulation, Your Password has been Reset',
            pass_enter:'Enter Your Password',
            pass_enter_again:'Enter Your Password Again',
            cash_message:"You can pay using vodafone cash at this number",
            cash_contact_message:"After Payment contact us and send the receipt (if available) at",
            fawery_soon:"Fawery will be available soon",
        },
        ar:{
            info:'المعلومات الشخصية',
            orders:'الطلبات',
            courses:'الدورات التدريبية',
            favourite:'التفضيلات',
            basic_info:'المعلومات الأساسية',
            change_pass:'تغيير كلمة المرور',
            update_address:'تعديل سجل العنوان',
            first_name:'الأسم الأول',
            first_name_holder:'اكتب الإسم الأول',
            last_name:'إسم العائلة',
            last_name_holder:'اكتب إسم العائلة',
            contact_info:'معلومات التواصل',
            mobile:'رقم الهاتف',
            mobile_holder:'اكتب رقم هاتفك ',
            email:'البريد الإلكترونى',
            email_holder:'اكتب بريدك الإلكترونى',
            pass:'كلمة المرور',
            pass_holder:'أكتب كلمة المرور',
            old_pass:'كلمة المرور القديمة',
            old_pass_holder:'اكتب كلمة المرور القديمة',
            new_pass:'كلمة المرور الجديدة',
            new_pass_holder:'اكتب كلمة المرور الجديدة',
            confirm_pass:'تاكيد كلمة المرور',
            confirm_pass_holder:'اكتب كلمة المرور الجديدة مرة أخرى',
            no_address:'لا يوجد اى عنوان حالياً',
            add_address_now:'أضف عنوانك الآن',
            add_address:'أضف العنوان',
            address_error:'خانة العنوان مطلوبة',
            city_error:'خانة المدينة مطلوبة',
            state_error:'خانة المحافظة /المنطقة / الولاية مطلوبة',
            country_error:'خانة الدولة مطلوبة',
            postalCode_error:'خانة الرقم البريدى مطلوبة',
            address_line:'العنوان الرئيسى',
            address_line_holder:'أدخل العنوان الرئيسى',
            country_select:'اختر اسم الدولة',
            state_enter:'أدخل اسم المحافظة او المنطقة',
            state_enter_holder:'أدخل اسم المحافظة او المنطقة',
            city_enter:'أدخل اسم المدينة',
            city_enter_holder:'أدخل اسم المدينة',
            postal_enter:'أدخل الرقم البريدى',
            postal_enter_holder:'أدخل الرقم البريدى',
            update:'تحديث',
            submit:'حفظ',
            save:'حفظ',
            order_history:'ارشيف الطلبات',
            downloads:'التحميلات',
            returns:'المرتجعات',
            payment_profile:'بيانات الدفع',
            order_no:'رقم الطلب',
            order_at:'تاريخ الطلب',
            payment_method:'طريقة الدفع',
            total:'الإجمالى',
            items_show:'عرض المنتجات',
            no_favourite:' لا يوجد منتجات فى سجل التفضيلات',
            browse_product:'تسوق المنتجات',
            item:'المنتج',
            price:'السعر',
            cart_add:'أضف الى عربة التسوق',
            delete:'حذف',
            sign_in:'دخول',
            sign_up:'تسجيل',    
            new_signup:'تسجيل حساب جديد',
            already_user:'تمتلك حساب بالفعل',
            full_name:'الإسم كاملاً',
            email_address:'البريد الإلكترونى',
            phone:'رقم الهاتف',
            phone_holder:'ادخل رقم هاتفك',
            agree_statement:'اوافق على',
            terms_of_service:'شروط الخدمة',
            terms_of_sales:'شروط البيع!',
            or_signup:'او يمكنك التسجيل',
            pass_rule:'كلمة المرور لابد ان تكون على الاقل ثمانى حروف باللغة الإنجليزية منهم حرف كبير وحرف وصغير ورقم ورمز كمثل #$%@',
            provide_data:'من فضلك اكتب البيانات المطلوبة',
            is_required:' من فضلك اكتب',
            pass_nomatch:'كلمات المرور غير متطابقة',
            is_agree:'من فضلك وافق على شروط البيع وشروط الخدمة!',
            email_enter:'أكتب بريديك الإلكترونى هنا',
            reset_link:'أرسل رابط إعادة الضبط',
            remember_me:'تذكرنى',
            pass_forget:'نسيت كلمة المرور؟',
            no_account:'لا تمتلك حساب؟',
            new_account:'أنشىء حساب',
            went_wrong:'حدث خطأ ما من فضلك حاول مجدداً',
            payment_cancel:'لقد تم إلغاء عملية الدفع',
            verify_email:'تهانينا تم تفعيل البريد الألكترونى',
            main_page_redirect:'أعادة التوجة الى صفحة الدخول فــ 5 ثوانى',
            invalid_token:'الرابط غير صالح ',
            not_match_pass:'كلمة المرور غير متطابقة, من فضلك اعد إدخال كلمة المرور',
            reset_pass_done:'تهانينا تم إعادة ضبط كلمة المرور',
            pass_enter:'أدخل كلمة المرور',
            pass_enter_again:'أدخل كلمة المرور مرة أخرى',
            cash_message:"يمكن الدفع باستخدام فودافون كاش عن طريق هذا الرقم",
            cash_contact_message:"بعد إتمام عملية الدفع يمكنك التواصل معنا وإرسال الإيصال )إن وجد لهذا البريد(",
            fawery_soon:"سيتم إضافة خدمة الدفع عن طريق فورى فى القريب العاجل",
        }
    },
    header: {
        en: {
            question: 'have any questions?',
            home: 'home',
            courses: 'courses',
            tunning: 'tunning files',
            blog: 'our blog',
            immo: 'immo off files',
            hardware: 'hardware tools',
            gallery: 'gallery',
            airbag: 'airbag clear crash',
            ecu: 'ecu programmers',
            contact: 'contact us',
            log: 'sign in'
        },
        ar: {
            question: "هل لديك اى سؤال؟",
            home: 'الصفحة الرئيسية',
            courses: 'الدورات التدريبية',
            tunning: 'ملفات التاننج',
            blog: 'المدونة',
            immo: 'ملفات Immo off',
            hardware: 'أدوات الهارد وير',
            gallery: 'الاستوديو',
            airbag: 'نتيجة تصادم airbag',
            ecu: 'برمجة ecu',
            contact: 'اتصل بنا',
            log: 'دخول'
        }
    },
    footer: {

        en: {
            account: 'account',
            fav: 'favourite',
            cart: 'my cart',
            support: 'support',
            privacy: 'privacy policy',
            about: 'about us',
            video: 'video gallery',
            photo: 'photo gallery',
            courses: 'courses',
            tunning: 'tunning files',
            blog: 'our blog',
            immo: 'immo off files',
            hardware: 'hardware tools',
            ecu: 'ecu programmers',
            help: 'Help'
        },
        ar: {
            account: 'الحساب',
            fav: 'التفضيلات',
            cart: 'عربة التسوق',
            support: 'الدعم',
            privacy: 'سياسة الخصوصية',
            about: 'نبذة عنا',
            video: 'قائمة الفيديوهات',
            photo: 'استوديو الصور',
            courses: 'الدورات التدريبية',
            tunning: 'ملفات التاننج',
            blog: 'المدونة',
            immo: 'ملفات Immo off',
            hardware: 'أدوات الهارد وير',
            ecu: 'برمجة ecu',
            help: 'المساعدة'
        }
    },
    main: {
        en: {
            feature_title: 'Elgendy Center',
            feature_first_header: 'Enjoy the best',
            feature_second_header: 'engineering',
            feature_text: 'courses in automotive',
            overview_online_courses_header:"online courses",
            overview_books_included_header:"Programs and books",
            overview_discount_included_header:"Big Discounts",
            overview_support_included_header:"Technical Support",
            overview_online_courses:"You can attend courses online from anywhere in the world with high quality videos and sound",
            overview_books_included:"You can get files, programs, and more from our library with our online courses",
            overview_discount_included:"Big discounts on gears and devices for you to get started",
            overview_support_included:"24/7 support from our experts",
            courses_title: 'Explore our Latest Courses',
            courses_download: 'Loading our Latest Courses....',
            instructor: 'Meet our Instructor'
        },
        ar: {
            feature_title:"مركز الجندى",
            feature_first_header: 'إستمتع بافضل',
            feature_second_header: 'السيارات',
            feature_text: 'الدورات التدريبية فى هندسة',
            courses_title: 'اكتشف احدث الدورات التدريبية',
            overview_online_courses_header:"دورات تدريبية مسجلة عن بعد",
            overview_books_included_header:"كتب وبرامج",
            overview_discount_included_header:"خصومات",
            overview_support_included_header:"دعم فنى",
            overview_online_courses:"تستطيع أن تحضر الدورات أون لاين مسجلة عن بعد من أي مكان بالعالم بجودة عالية الدقة صوتًا وصورة.",
            overview_books_included:"تستطيع الحصول على ملفات وبرامج وكتب هدايا مجانية مع الدورات التدريبية.",
            overview_discount_included:"خصومات كبيرة على الأجهزة والمعدات للحاصلين على الدورات التدريبية",
            overview_support_included:"دعم فني على مدار 12 ساعة يوميًا",
            courses_download: '....جارى تحميل احدث الدورات التدريبية',
            instructor: 'تعرف على المدرب'
        }
    },
    course: {
        en: {
            read_more: 'read more',
            read_less: 'read less',
            course_load: 'Loading The Course Data....',
            requirements: 'Requirements',
            description: 'Description',
            who: 'Who this course is for:',
            no_requirements: 'there is no requirements for this course',
            course_content: 'Course Content',
            instructor: 'Instructor',
            feedback: 'Student Feedback',
            student: 'student',
            students: 'Students',
            rating: 'rating',
            created: 'Created By:',
            last_updated: 'Last Updated:',
            wishlist: 'Wishlist',
            share: 'share',
            gift: 'Gift this Course',
            apply: 'Apply',
            enroll: 'Enroll Now',
            enrolled_course: 'Go to Course',
            enrolled_date: 'You enrolled in this course on',
            free: 'Free Course',
            include: 'This Course includes:',
            lifetime: 'Full lifetime access',
            duration:'on-demand videos',
            responsive: 'Access on mobile and TV',
            certificate: 'Certificate of completion',
            points: 'What You will learn',
            course_rating: 'Course Rating',
            content: 'Content',
            overview: 'overview',
            notes: 'Notes',
            announcements: 'Announcements',
            by_numbers: 'By the numbers',
            skill_level: 'Skill Level',
            all_level: 'All Levels',
            languages: 'Languages',
            caption: 'Caption',
            lectures: 'Lectures',
            videos: 'Videos',
            features: 'Features',
            create_note: 'Click to Create note',
            announcement_date: 'Posted an announcement',
            show: 'show',
            hide: 'hide',
            all_comments: 'all comments',
            since: 'since',
            summery: 'Summery',
            original_price: 'Original price:',
            coupon_discounts: 'Coupon discounts:',
            total: 'Total:',
            off:'off',
            rating_course:'Course Rating',
            save:'save',
            cancel:'cancel',
            update:'update',
            hour:'hour',
            courses_load:'Loading Courses.....',
            add_wishlist:'add to wishlist',
            remove_wishlist:'remove from wishlist',
            download_link_added:'Course Download Links has been added to your download section '
        },
        ar: {
            read_more: 'قراءة المزيد',
            read_less: 'قراءة أقل',
            course_load: '....تحميل بيانات الدورة التدريبية',
            requirements: 'متطلبات الدروة التدريبية',
            description: 'وصف الدورة التدريبية',
            who: 'لمن هذة الدورة التدريبية:',
            no_requirements: 'ليس هناك متطلبات لهذة الدروة التدريبية',
            course_content: 'محتوى الدورة التدريبية',
            instructor: 'المدرب',
            feedback: 'آراء المتدربين',
            student: 'طالب',
            students: 'طلبة',
            rating: 'تقييم',
            created: 'المدرب:',
            last_updated: 'آخر تحديث:',
            wishlist: 'التفضيلات',
            share: 'مشاركة',
            gift: 'إهداء الدورة التدريبية',
            apply: 'طلب الكود',
            enroll: 'التحق الآن',
            enrolled_course: 'إستكمال الدورة التدريبية',
            enrolled_date: 'لقد التحقت بهذا الكورس بتاريخ',
            free: 'دورة تدريبية مجانية',
            include: ':تحتوى الدورة التدريبية على',
            lifetime: 'التحاق مدى الحياة',
            duration:'مدة المحتوى',
            responsive: 'مشاهدة على الموبايل والتلفاز',
            certificate: 'شهادة اتمام الدورة التدريبية',
            points: 'ماذا سوف تتعلم من الدورة التدريبية',
            course_rating: 'تقييم الدورة التدريبية',
            content: 'المحتوى',
            overview: 'نظرة عامة',
            notes: 'ملاحظات',
            announcements: 'الإشعارات',
            by_numbers: 'نظرة بالأرقام',
            skill_level: 'مستوى المهارة',
            all_level: 'كل المستويات',
            languages: 'اللغة',
            caption: 'ترجمة',
            lectures: 'محاضرات',
            videos: 'مدة الفيديوهات',
            features: 'الخصائص',
            create_note: 'إضغط هنا لكتابة ملاحظة',
            announcement_date: 'تم نشر الاشعار',
            show: 'إظهار',
            hide: 'إخفاء',
            all_comments: 'جميع التعليقات',
            since: 'منذ',
            summery: 'ملخص الدفع',
            original_price: 'السعر الأصلى:',
            coupon_discounts: 'كوبون الخصم:',
            total: 'الإجمالى:',
            off:'خصم',
            rating_course:'تقييم الدورة',
            save:'حفظ',
            cancel:'الغاء',
            update:'تحديث',
            hour:'ساعة',
            courses_load:'جارى تحميل الدورات التدريبية.....',
            add_wishlist:'أضف الى قائمة التفضيلات',
            remove_wishlist:'حذف من قائمة التفضيلات',
            prepare_download_link:'تجهيز رابط التحميل الآن...',
            download_link_added:'تم إضافة روابط التحميل فى قسم التحميلات الخاص بك'
        }
    },
    product: {
        en: {
            details: 'Details',
            cart: 'Add to Cart',
            cart_name:'Cart',
            payment:'Payment',
            delivery:'Delivery',
            done:'done',
            product_load:'Loading Product....',
            description:'Product Description',
            stock:'In Stock',
            qty:'Quantity',
            price:'Price',
            call:'Call us',
            book:'book call',
            addWishlist:'Add to Wishlist',
            removeWishlist:'Remove from Wishlist',
            next:'next',
            contact_method:'choose your contact method ?',
            phone:'Phone Call',
            zoom:'Zoom Meeting',
            whats:'WhatsApp Chat',
            phone_number:'Enter your phone number',
            set_date:'Set Date',
            time:'Time',
            date:'Date',
            pick:'Pick Date & Time',
            item:'Item',
            total:'Total',
            continue_shopping:'Continue Shopping',
            checkout:'Checkout',
            no_items:'No Items in the Cart',
            items_list:'Here are a list of your purchased products',
            purchase_thank:'Thank You for Purchasing our Products',
            order_no:'Order NO :',
            products_load:'Loading Products....',
            download_product:'Download File',
            download_link_added:"Product Download Links has been added to your download section",
            item_added_to_cart:"Item has been added to your cart",
        },
        ar: {
            details: 'التفاصيل',
            cart: 'أضف الى عربة التسوق',
            cart_name:'عربة التسوق',
            payment:'الدفع',
            delivery:'التوصيل',
            done:'تم',
            product_load: '....تحميل المنتجات',
            description:'وصف المنتج',
            stock:'الموجود حالياً',
            qty:'الكمية',
            price:'السعر',
            call:'إتصل بنا',
            book:'إحجز مكالمة',
            addWishlist:'أضف الى قائمة التفضيلات',
            removeWishlist:'حذف من قائمة التفضيلات',
            next:'التالى',
            contact_method:'أختر وسيلة التواصل ؟',
            phone:'عن طريق الهاتف',
            zoom:'اجتماع عبر برنامج زووم',
            whats:'WhatsApp محادثة',
            phone_number:'إدخل رقم هاتفك',
            set_date:'حدد التاريخ',
            time:'الوقت',
            date:'التاريخ',
            pick:'إختر التاريخ والوقت',
            item:'المنتج',
            total:'الإجمالى',
            continue_shopping:'متابعة التسوق',
            checkout:'إتمام الشراء',
            no_items:'عربة التسوق خالية',
            items_list:'قائمة بالمنتجات التى تم شرائها',
            purchase_thank:'شكراً على شرائك منتجاتنا',
            order_no:'رقم الطلب :',
            products_load:'جارى تحميل المنتجات....',
            download_product:'تحميل الملف',
            download_link_added:'تم إضافة روابط تحميل المنتج فى قسم التحميلات الخاص بك',
            item_added_to_cart:'تم إضافة المنتج الى عربة التسوق',
        }
    },
    blog:{
        en:{
            read_less:'read less',
            read_more:'read more',
            leave_comment:'Leave Your Comment Here',
            blog_load:'Loading Blog....',
            log_comment:'Log In to Add a Comment'
        },
        ar:{
            read_more: 'قراءة المزيد',
            read_less: 'قراءة أقل',
            leave_comment:'أكتب تعليقك هنا',
            blog_load: '....تحميل المدونة',
            log_comment:'سجل الدخول لإضافة تعليق'
               
        }
    },
    gallery:{
        en:{
            photo_gallery:'Photo Gallery',
            photo_switch:'Switch to Photo Gallery',
            video_gallery:'Video Gallery',
            video_switch:'Switch to Video Gallery',
            views:'views'
        },
        ar:{
            photo_gallery:'مكتبة الصور',
            photo_switch:'الإنتقال الى مكتبة الصور',
            video_gallery:'مكتبة الفيديوهات',
            video_switch:'الإنتقال الى مكتبة الفيديوهات',
            views:'مشاهدة'
        }
    },
    contact:{
        en:{
            send:'send us a message',
            name:'Your Name',
            phone:'Your Phone',
            email:'Your E-mail Address',
            message:'Your Message here....',
            call:'Call Us',
            book:'Book a Call',
            submit:'submit',
            location:'find our location in google maps',
            contact_message:'You can book a call or send us a message and we will contact you as soon as possible',
            done:'DONE'
        },
        ar:{
            send:'أرسل لنا رسالة',
            name:'أكتب اسمك',
            phone:'أكتب رقم هاتفك',
            email:'أكتب بريديك الإلكترونى',
            message:'اكتب رسالتك هنا...',
            call:'إتصل بنا',
            book:'إحجز مكالمة',
            submit:'أرسل',
            location:'حدد موقعنا على خرائط جوجل',
            contact_message:"بإمكانك حجز مكالمتك او إرسالة رسالة في أي وقت وسيتم التواصل معك مباشرة في الموعد المحدد",
            done:'تم'
        }
    }
}

export default strings
