const blog = {
    LIST_BLOGS_REQUEST:  'LIST_BLOGS_REQUEST',
    LIST_BLOGS_SUCCESS:  'LIST_BLOGS_SUCCESS',
    LIST_BLOGS_FAIL   :  'LIST_BLOGS_FAIL',
    LIST_BLOGS_RESET  :  'LIST_BLOGS_RESET',

    GET_BLOG_REQUEST:  'GET_BLOG_REQUEST',
    GET_BLOG_SUCCESS:  'GET_BLOG_SUCCESS',
    GET_BLOG_FAIL   :  'GET_BLOG_FAIL',
    GET_BLOG_RESET  :  'GET_BLOG_RESET',

    CONTROL_BLOG_VIEWS_REQUEST:  'CONTROL_BLOG_VIEWS_REQUEST',
    CONTROL_BLOG_VIEWS_SUCCESS:  'CONTROL_BLOG_VIEWS_SUCCESS',
    CONTROL_BLOG_VIEWS_FAIL   :  'CONTROL_BLOG_VIEWS_FAIL',
    CONTROL_BLOG_VIEWS_RESET  :  'CONTROL_BLOG_VIEWS_RESET',

    LIST_BLOG_COMMENTS_REQUEST:  'LIST_BLOG_COMMENTS_REQUEST',
    LIST_BLOG_COMMENTS_SUCCESS:  'LIST_BLOG_COMMENTS_SUCCESS',
    LIST_BLOG_COMMENTS_FAIL   :  'LIST_BLOG_COMMENTS_FAIL',
    LIST_BLOG_COMMENTS_RESET  :  'LIST_BLOG_COMMENTS_RESET',

    ADD_BLOG_COMMENT_REQUEST:  'ADD_BLOG_COMMENT_REQUEST',
    ADD_BLOG_COMMENT_SUCCESS:  'ADD_BLOG_COMMENT_SUCCESS',
    ADD_BLOG_COMMENT_FAIL   :  'ADD_BLOG_COMMENT_FAIL',
    ADD_BLOG_COMMENT_RESET  :  'ADD_BLOG_COMMENT_RESET',

    DELETE_BLOG_COMMENT_REQUEST:  'DELETE_BLOG_COMMENT_REQUEST',
    DELETE_BLOG_COMMENT_SUCCESS:  'DELETE_BLOG_COMMENT_SUCCESS',
    DELETE_BLOG_COMMENT_FAIL   :  'DELETE_BLOG_COMMENT_FAIL',
    DELETE_BLOG_COMMENT_RESET  :  'DELETE_BLOG_COMMENT_RESET',
}

export default blog