const client = {
    // CLIENT REGISTER
    REGISTER_REQUEST: 'CLIENT_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'CLIENT_REGISTER_SUCCESS',
    REGISTER_FAIL: 'CLIENT_REGISTER_FAIL',
    REGISTER_RESET: 'CLIENT_REGISTER_RESET',

    // CLIENT LOGIN
    LOGIN_REQUEST: 'CLIENT_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'CLIENT_LOGIN_SUCCESS',
    LOGIN_FAIL: 'CLIENT_LOGIN_FAIL',
    LOGIN_CLEAR: 'CLIENT_LOGIN_CLEAR',
    LOGIN_RESET: 'CLIENT_LOGIN_RESET',

    // CLIENT LOGOUT
    LOGOUT_REQUEST: 'CLIENT_LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'CLIENT_LOGOUT_SUCCESS',
    LOGOUT_FAIL: 'CLIENT_LOGOUT_FAIL',
    LOGOUT_RESET: 'CLIENT_LOGOUT_RESET',

    // CLIENT UPDATE INFO
    UPDATE_REQUEST: 'CLIENT_UPDATE_REQUEST',
    UPDATE_SUCCESS: 'CLIENT_UPDATE_SUCCESS',
    UPDATE_FAIL: 'CLIENT_UPDATE_FAIL',
    UPDATE_RESET: 'CLIENT_UPDATE_RESET',
    
    // CLIENT UPDATE PASSWORD
    UPDATE_PASSWORD_REQUEST: 'CLIENT_UPDATE_PASSWORD_REQUEST',
    UPDATE_PASSWORD_SUCCESS: 'CLIENT_UPDATE_PASSWORD_SUCCESS',
    UPDATE_PASSWORD_FAIL: 'CLIENT_UPDATE_PASSWORD_FAIL',
    UPDATE_PASSWORD_RESET: 'CLIENT_UPDATE_PASSWORD_RESET',

    // CLIENT VERIFY EMAIL
    VERIFY_EMAIL_REQUEST: 'CLIENT_VERIFY_EMAIL_REQUEST',
    VERIFY_EMAIL_SUCCESS: 'CLIENT_VERIFY_EMAIL_SUCCESS',
    VERIFY_EMAIL_FAIL: 'CLIENT_VERIFY_EMAIL_FAIL',
    VERIFY_EMAIL_RESET: 'CLIENT_VERIFY_EMAIL_RESET',

    // CLIENT RESET PASSWORD
    RESET_PASSWORD_REQUEST: 'CLIENT_RESET_PASSWORD_REQUEST',
    RESET_PASSWORD_SUCCESS: 'CLIENT_RESET_PASSWORD_SUCCESS',
    RESET_PASSWORD_FAIL: 'CLIENT_RESET_PASSWORD_FAIL',
    RESET_PASSWORD_RESET: 'CLIENT_RESET_PASSWORD_RESET',

    // CLIENT RESET PASSWORD LINK
    RESET_PASSWORD_LINK_REQUEST: 'CLIENT_RESET_PASSWORD_LINK_REQUEST',
    RESET_PASSWORD_LINK_SUCCESS: 'CLIENT_RESET_PASSWORD_LINK_SUCCESS',
    RESET_PASSWORD_LINK_FAIL: 'CLIENT_RESET_PASSWORD_LINK_FAIL',
    RESET_PASSWORD_LINK_RESET: 'CLIENT_RESET_PASSWORD_LINK_RESET',

    // CLIENT GOOGLE SIGN IN
    GOOGLE_SIGN_IN_REQUEST: 'CLIENT_GOOGLE_SIGN_IN_REQUEST',
    GOOGLE_SIGN_IN_SUCCESS: 'CLIENT_GOOGLE_SIGN_IN_SUCCESS',
    GOOGLE_SIGN_IN_FAIL: 'CLIENT_GOOGLE_SIGN_IN_FAIL',

    // CLIENT GOOGLE SIGN IN
    FACEBOOK_SIGN_IN_REQUEST: 'CLIENT_FACEBOOK_SIGN_IN_REQUEST',
    FACEBOOK_SIGN_IN_SUCCESS: 'CLIENT_FACEBOOK_SIGN_IN_SUCCESS',
    FACEBOOK_SIGN_IN_FAIL: 'CLIENT_FACEBOOK_SIGN_IN_FAIL',
    FACEBOOK_SIGN_IN_RESET: 'CLIENT_FACEBOOK_SIGN_IN_RESET',
}

export default client