const constants = {
  LIST_NAV_ITEMS_REQUEST: 'LIST_NAV_ITEMS_REQUEST',
  LIST_NAV_ITEMS_SUCCESS: 'LIST_NAV_ITEMS_SUCCESS',
  LIST_NAV_ITEMS_FAIL: 'LIST_NAV_ITEMS_FAIL',
  LIST_NAV_ITEMS_RESET: 'LIST_NAV_ITEMS_RESET',

  LIST_GALLERY_ITEMS_REQUEST: 'LIST_GALLERY_ITEMS_REQUEST',
  LIST_GALLERY_ITEMS_SUCCESS: 'LIST_GALLERY_ITEMS_SUCCESS',
  LIST_GALLERY_ITEMS_FAIL: 'LIST_GALLERY_ITEMS_FAIL',
  LIST_GALLERY_ITEMS_RESET: 'LIST_GALLERY_ITEMS_RESET',
}

export default constants
