const contact = {
    SEND_CONTACT_REQUEST:'SEND_CONTACT_REQUEST',
    SEND_CONTACT_SUCCESS:'SEND_CONTACT_SUCCESS',
    SEND_CONTACT_FAIL:'SEND_CONTACT_FAIL',
    SEND_CONTACT_RESET:'SEND_CONTACT_RESET',
}

export default contact