const courses = {
    // COURSES CONSTANTS
    LIST_ALL_REQUEST : 'LIST_ALL_REQUEST',
    LIST_ALL_SUCCESS : 'LIST_ALL_SUCCESS',
    LIST_ALL_FAIL : 'LIST_ALL_FAIL',

    GET_ONE_REQUEST : 'GET_ONE_REQUEST',
    GET_ONE_SUCCESS : 'GET_ONE_SUCCESS',
    GET_ONE_FAIL : 'GET_ONE_FAIL',
    GET_ONE_RESET : 'GET_ONE_RESET',

    // CHAPTERS CONSTANTS
    LIST_CHAPTERS_REQUEST : 'LIST_CHAPTERS_REQUEST',
    LIST_CHAPTERS_SUCCESS : 'LIST_CHAPTERS_SUCCESS',
    LIST_CHAPTERS_FAIL : 'LIST_CHAPTERS_FAIL',

    // ENROLLMENT CONSTANTS
    NEW_ENROLLMENT_REQUEST : 'NEW_ENROLLMENT_REQUEST',
    NEW_ENROLLMENT_SUCCESS : 'NEW_ENROLLMENT_SUCCESS',
    NEW_ENROLLMENT_FAIL : 'NEW_ENROLLMENT_FAIL',
    NEW_ENROLLMENT_RESET : 'NEW_ENROLLMENT_RESET',

    GET_ENROLLMENT_REQUEST : 'GET_ENROLLMENT_REQUEST',
    GET_ENROLLMENT_SUCCESS : 'GET_ENROLLMENT_SUCCESS',
    GET_ENROLLMENT_FAIL : 'GET_ENROLLMENT_FAIL',
    GET_ENROLLMENT_RESET : 'GET_ENROLLMENT_RESET',

    ENROLLMENT_PROGRESS_REQUEST : 'ENROLLMENT_PROGRESS_REQUEST',
    ENROLLMENT_PROGRESS_SUCCESS : 'ENROLLMENT_PROGRESS_SUCCESS',
    ENROLLMENT_PROGRESS_FAIL : 'ENROLLMENT_PROGRESS_FAIL',

    // NOTES CONSTANTS
    LIST_NOTES_REQUEST : 'LIST_NOTES_REQUEST',
    LIST_NOTES_SUCCESS : 'LIST_NOTES_SUCCESS',
    LIST_NOTES_FAIL : 'LIST_NOTES_FAIL',

    CREATE_NOTE_REQUEST : 'CREATE_NOTE_REQUEST',
    CREATE_NOTE_SUCCESS : 'CREATE_NOTE_SUCCESS',
    CREATE_NOTE_FAIL : 'CREATE_NOTE_FAIL',
    CREATE_NOTE_RESET : 'CREATE_NOTE_RESET',

    UPDATE_NOTE_REQUEST : 'UPDATE_NOTE_REQUEST',
    UPDATE_NOTE_SUCCESS : 'UPDATE_NOTE_SUCCESS',
    UPDATE_NOTE_FAIL : 'UPDATE_NOTE_FAIL',
    UPDATE_NOTE_RESET : 'UPDATE_NOTE_RESET',

    DELETE_NOTE_REQUEST : 'DELETE_NOTE_REQUEST',
    DELETE_NOTE_SUCCESS : 'DELETE_NOTE_SUCCESS',
    DELETE_NOTE_FAIL : 'DELETE_NOTE_FAIL',
    DELETE_NOTE_RESET : 'DELETE_NOTE_RESET',

    // ANNOUNCEMENTS CONSTANTS
    LIST_ANNOUNCEMENTS_REQUEST : 'LIST_ANNOUNCEMENTS_REQUEST',
    LIST_ANNOUNCEMENTS_SUCCESS : 'LIST_ANNOUNCEMENTS_SUCCESS',
    LIST_ANNOUNCEMENTS_FAIL : 'LIST_ANNOUNCEMENTS_FAIL',

    LIST_ANNOUNCEMENT_COMMENTS_REQUEST : 'LIST_ANNOUNCEMENT_COMMENTS_REQUEST',
    LIST_ANNOUNCEMENT_COMMENTS_SUCCESS : 'LIST_ANNOUNCEMENT_COMMENTS_SUCCESS',
    LIST_ANNOUNCEMENT_COMMENTS_FAIL : 'LIST_ANNOUNCEMENT_COMMENTS_FAIL',

    ADD_ANNOUNCEMENT_COMMENT_REQUEST : 'ADD_ANNOUNCEMENT_COMMENT_REQUEST',
    ADD_ANNOUNCEMENT_COMMENT_SUCCESS : 'ADD_ANNOUNCEMENT_COMMENT_SUCCESS',
    ADD_ANNOUNCEMENT_COMMENT_FAIL : 'ADD_ANNOUNCEMENT_COMMENT_FAIL',
    ADD_ANNOUNCEMENT_COMMENT_RESET : 'ADD_ANNOUNCEMENT_COMMENT_RESET',

    DELETE_ANNOUNCEMENT_COMMENT_REQUEST : 'DELETE_ANNOUNCEMENT_COMMENT_REQUEST',
    DELETE_ANNOUNCEMENT_COMMENT_SUCCESS : 'DELETE_ANNOUNCEMENT_COMMENT_SUCCESS',
    DELETE_ANNOUNCEMENT_COMMENT_FAIL : 'DELETE_ANNOUNCEMENT_COMMENT_FAIL',
    DELETE_ANNOUNCEMENT_COMMENT_RESET : 'DELETE_ANNOUNCEMENT_COMMENT_RESET',

    ADD_COURSE_TO_WISHLIST_REQUEST:'ADD_COURSE_TO_WISHLIST_REQUEST',
    ADD_COURSE_TO_WISHLIST_SUCCESS:'ADD_COURSE_TO_WISHLIST_SUCCESS',
    ADD_COURSE_TO_WISHLIST_FAIL:'ADD_COURSE_TO_WISHLIST_FAIL',
    ADD_COURSE_TO_WISHLIST_RESET:'ADD_COURSE_TO_WISHLIST_RESET',

    REMOVE_COURSE_FROM_WISHLIST_REQUEST:'REMOVE_COURSE_FROM_WISHLIST_REQUEST',
    REMOVE_COURSE_FROM_WISHLIST_SUCCESS:'REMOVE_COURSE_FROM_WISHLIST_SUCCESS',
    REMOVE_COURSE_FROM_WISHLIST_FAIL:'REMOVE_COURSE_FROM_WISHLIST_FAIL',
    REMOVE_COURSE_FROM_WISHLIST_RESET:'REMOVE_COURSE_FROM_WISHLIST_RESET',

    VERIFY_COUPON_REQUEST: 'VERIFY_COUPON_REQUEST',
    VERIFY_COUPON_SUCCESS: 'VERIFY_COUPON_SUCCESS',
    VERIFY_COUPON_FAIL: 'VERIFY_COUPON_FAIL',
    VERIFY_COUPON_RESET: 'VERIFY_COUPON_RESET',

    // LIST PURCHASED COURSES
    LIST_PURCHASED_COURSES_REQUEST : 'LIST_PURCHASED_COURSES_REQUEST',
    LIST_PURCHASED_COURSES_SUCCESS : 'LIST_PURCHASED_COURSES_SUCCESS',
    LIST_PURCHASED_COURSES_FAIL : 'LIST_PURCHASED_COURSES_FAIL',

    //  ADD COURSE REVIEW
    ADD_REVIEW_REQUEST:'ADD_REVIEW_REQUEST',   
    ADD_REVIEW_SUCCESS:'ADD_REVIEW_SUCCESS',   
    ADD_REVIEW_FAIL:'ADD_REVIEW_FAIL',  
    ADD_REVIEW_RESET:'ADD_REVIEW_RESET',  

    //  GET COURSE REVIEW
    GET_REVIEW_REQUEST:'GET_REVIEW_REQUEST',   
    GET_REVIEW_SUCCESS:'GET_REVIEW_SUCCESS',   
    GET_REVIEW_FAIL:'GET_REVIEW_FAIL', 
    GET_REVIEW_RESET:'GET_REVIEW_RESET', 

    //  UPDATE COURSE REVIEW
    UPDATE_REVIEW_REQUEST:'UPDATE_REVIEW_REQUEST',   
    UPDATE_REVIEW_SUCCESS:'UPDATE_REVIEW_SUCCESS',   
    UPDATE_REVIEW_FAIL:'UPDATE_REVIEW_FAIL', 
    UPDATE_REVIEW_RESET:'UPDATE_REVIEW_RESET',

     //  Download Course Asset
     DOWNLOAD_ASSET_REQUEST:'DOWNLOAD_ASSET_REQUEST',   
     DOWNLOAD_ASSET_SUCCESS:'DOWNLOAD_ASSET_SUCCESS',   
     DOWNLOAD_ASSET_FAIL:'DOWNLOAD_ASSET_FAIL', 
     DOWNLOAD_ASSET_RESET:'DOWNLOAD_ASSET_RESET',

    DELETE_ASSET_PERMISSION_REQUEST:'DELETE_ASSET_PERMISSION_REQUEST',
    DELETE_ASSET_PERMISSION_SUCCESS:'DELETE_ASSET_PERMISSION_SUCCESS',
    DELETE_ASSET_PERMISSION_FAIL:'DELETE_ASSET_PERMISSION_FAIL',
    DELETE_ASSET_PERMISSION_RESET:'DELETE_ASSET_PERMISSION_RESET',
}

export default courses