const product = {
    LIST_PRODUCTS_REQUEST: 'LIST_PRODUCTS_REQUEST',
    LIST_PRODUCTS_SUCCESS: 'LIST_PRODUCTS_SUCCESS',
    LIST_PRODUCTS_FAIL   : 'LIST_PRODUCTS_FAIL',
    LIST_PRODUCTS_RESET  : 'LIST_PRODUCTS_RESET',

    GET_PRODUCT_REQUEST: 'GET_PRODUCT_REQUEST',
    GET_PRODUCT_SUCCESS: 'GET_PRODUCT_SUCCESS',
    GET_PRODUCT_FAIL   : 'GET_PRODUCT_FAIL',
    GET_PRODUCT_RESET  : 'GET_PRODUCT_RESET',

    ADD_PRODUCT_TO_WISHLIST_REQUEST: 'ADD_PRODUCT_TO_WISHLIST_REQUEST',
    ADD_PRODUCT_TO_WISHLIST_SUCCESS: 'ADD_PRODUCT_TO_WISHLIST_SUCCESS',
    ADD_PRODUCT_TO_WISHLIST_FAIL: 'ADD_PRODUCT_TO_WISHLIST_FAIL',
    ADD_PRODUCT_TO_WISHLIST_RESET: 'ADD_PRODUCT_TO_WISHLIST_RESET',

    REMOVE_PRODUCT_FROM_WISHLIST_REQUEST: 'REMOVE_PRODUCT_FROM_WISHLIST_REQUEST',
    REMOVE_PRODUCT_FROM_WISHLIST_SUCCESS: 'REMOVE_PRODUCT_FROM_WISHLIST_SUCCESS',
    REMOVE_PRODUCT_FROM_WISHLIST_FAIL: 'REMOVE_PRODUCT_FROM_WISHLIST_FAIL',
    REMOVE_PRODUCT_FROM_WISHLIST_RESET: 'REMOVE_PRODUCT_FROM_WISHLIST_RESET',
    
    CREATE_ORDER_REQUEST: 'CREATE_ORDER_REQUEST',
    CREATE_ORDER_SUCCESS: 'CREATE_ORDER_SUCCESS',
    CREATE_ORDER_FAIL   : 'CREATE_ORDER_FAIL',
    CREATE_ORDER_RESET  : 'CREATE_ORDER_RESET',

    GET_ORDER_REQUEST: 'GET_ORDER_REQUEST',
    GET_ORDER_SUCCESS: 'GET_ORDER_SUCCESS',
    GET_ORDER_FAIL   : 'GET_ORDER_FAIL',
    GET_ORDER_RESET  : 'GET_ORDER_RESET',

    LIST_ORDERS_REQUEST: 'LIST_ORDERS_REQUEST',
    LIST_ORDERS_SUCCESS: 'LIST_ORDERS_SUCCESS',
    LIST_ORDERS_FAIL   : 'LIST_ORDERS_FAIL',
    LIST_ORDERS_RESET  : 'LIST_ORDERS_RESET',

    UPDATE_ORDER_REQUEST: 'UPDATE_ORDER_REQUEST',
    UPDATE_ORDER_SUCCESS: 'UPDATE_ORDER_SUCCESS',
    UPDATE_ORDER_FAIL   : 'UPDATE_ORDER_FAIL',
    UPDATE_ORDER_RESET  : 'UPDATE_ORDER_RESET',

    LIST_CART_ITEMS_REQUEST: 'LIST_CART_ITEMS_REQUEST',
    LIST_CART_ITEMS_SUCCESS: 'LIST_CART_ITEMS_SUCCESS',
    LIST_CART_ITEMS_FAIL: 'LIST_CART_ITEMS_FAIL',
    LIST_CART_ITEMS_RESET: 'LIST_CART_ITEMS_RESET',
    
    ADD_ITEM_TO_CART_REQUEST: 'ADD_ITEM_TO_CART_REQUEST',
    ADD_ITEM_TO_CART_SUCCESS: 'ADD_ITEM_TO_CART_SUCCESS',
    ADD_ITEM_TO_CART_FAIL: 'ADD_ITEM_TO_CART_FAIL',
    ADD_ITEM_TO_CART_RESET: 'ADD_ITEM_TO_CART_RESET',
    
    REMOVE_ITEM_FROM_CART_REQUEST: 'REMOVE_ITEM_FROM_CART_REQUEST',
    REMOVE_ITEM_FROM_CART_SUCCESS: 'REMOVE_ITEM_FROM_CART_SUCCESS',
    REMOVE_ITEM_FROM_CART_FAIL: 'REMOVE_ITEM_FROM_CART_FAIL',
    REMOVE_ITEM_FROM_CART_RESET: 'REMOVE_ITEM_FROM_CART_RESET',

    CLEAR_CART_REQUEST: 'CLEAR_CART_REQUEST',
    CLEAR_CART_SUCCESS: 'CLEAR_CART_SUCCESS',
    CLEAR_CART_FAIL: 'CLEAR_CART_FAIL',
    CLEAR_CART_RESET: 'CLEAR_CART_RESET',

    LIST_FAVOURITE_PRODUCTS_REQUEST: 'LIST_FAVOURITE_PRODUCTS_REQUEST',
    LIST_FAVOURITE_PRODUCTS_SUCCESS: 'LIST_FAVOURITE_PRODUCTS_SUCCESS',
    LIST_FAVOURITE_PRODUCTS_FAIL   : 'LIST_FAVOURITE_PRODUCTS_FAIL',
    LIST_FAVOURITE_PRODUCTS_RESET  : 'LIST_FAVOURITE_PRODUCTS_RESET',

    BOOK_CALL_REQUEST:'BOOK_CALL_REQUEST',
    BOOK_CALL_SUCCESS:'BOOK_CALL_SUCCESS',
    BOOK_CALL_FAIL:'BOOK_CALL_FAIL',
    BOOK_CALL_RESET:'BOOK_CALL_RESET',
}

export default product