const lists = [    
    [
        {
            title:'immo',
            link:'/products?type=immo'
        },
        {
            title:'hardware',
            link:'/products?type=hardware'
        },
        {
            title:'tunning',
            link:'/products?type=tunning'
        },
        {
            title:'courses',
            link:'/courses'
        },
        {
            title:'blog',
            link:'/blogs'
        },
        {
            title:'ecu',
            link:'/products?type=ecu'
        }
    ],
    [
        {
            title:'account',
            link:'/account#info'
        },
        {
            title:'fav',
            link:'/account#favourites'
        },
        {
            title:'cart',
            link:'/order?process=cart'
        }
    ],
    [
        {
            title:'support',
            link:'/contact-us'
        },
        {
            title:'privacy',
            link:'/privacy-policy'
        },
    ],
    [
        {
            title:'video',
            link:'/videos-gallery'
        },
        {
            title:'photo',
            link:'/photo-gallery'
        }
    ]
 ]

 export default lists