export {default as Login } from './Login/Login'
export {default as Profile} from './Profile/Profile'
export {default as Dashboard} from './Dashboard/Dashboard'
export {default as Notifications} from './Notifications/Notifications'
export {default as Messages} from './Messages/Messages'
export {default as Users} from './Users/Users'
export {default as Products} from './Products/Products'
export {default as Product} from './Product/Product'
export {default as NewProduct} from './NewProduct/NewProduct'
export {default as Orders} from './Orders/Orders'
export {default as Blogs} from './Blogs/Blogs'
export {default as Blog} from './Blog/Blog'
export {default as NewBlog} from './NewBlog/NewBlog'
export {default as NotFound} from './NotFound/NotFound'
