export const items = [
    {
        title:'home',
        link:'/'
    },
    {
        title:'courses',
        link:'/courses'
    },
    {
        title:'tunning',
        link:'/products?type=tunning-files'
    },
    {
        title:'blog',
        link:'/blogs'
    },
    {
        title:'immo',
        link:'/products?type=immo-off-files'
    },
    {
        title:'hardware',
        link:'/products?type=hardware-tools'
    },
    {
        title:'gallery',
        link:'/photo-gallery'
    },
    {
        title:'airbag',
        link:'/products?type=air-bag-clear-crash'
    },
    {
        title:'ecu',
        link:'/products?type=ecu-programming'
    },
    {
        title:'contact',
        link:'/contact-us'
    }
]
